### ISSUE TITLE
GPU with voxel reuse plot

### ISSUE THREAD

**Issue by ammilten** [juliohm/ImageQuilting.jl#11]
I'm a bit confused about how the voxel reuse plot is implemented. It seems that the helper function `voxelreuse` has an option for using the GPU but `voxelreuseplot` does not. I don't really know how Recipes work in Julia but is there an easy way to add a GPU argument to `voxelreuseplot`?

**Comment by juliohm** [comment]
Good catch @ammilten, I don't remember adding the option to the plot recipe. I can fix that.

Meanwhile, you can hack the `plot_recipe.jl` file [here](https://github.com/juliohm/ImageQuilting.jl/blob/master/src/plot_recipes.jl#L80) and pass the option `gpu=true`.

**Comment by ammilten** [comment]
Great, that would be very useful. I am trying to learn more about how the recipes work so I can just fix it myself but the documentation is a bit confusing. Ideally I would think that the `voxelreuseplot` should have arguments for all of the arguments in `voxelreuse`.

**Comment by juliohm** [comment]
Plot recipes are not easy to grasp, it took me a while to get used to them. Thanks for the intention to fix it yourself though. I will submit a fix including all options :+1:

**Comment by juliohm** [comment]
I will reopen the issue to keep track of things. It should be closed automatically by GitHub when I submit the fix.
