### ISSUE TITLE
hard data issue

### ISSUE THREAD

**Issue by mariosgeo** [juliohm/ImageQuilting.jl#14]
Hi,

I am using the ImageQuilting toolbox to generate realizations of subsurface.
On the attached image, the left figure if the training image, the right figure is the borehole location and the center is one of the realizations. 

The windows used in iqsim is 40x40. Apparently, this is much bigger than the actual distance between two boreholes.  How can I use more efficiently the simulation ? Reducing the window or am I doing something wrong?

![figure_1-1](https://user-images.githubusercontent.com/3422736/44411116-17d6cb00-a566-11e8-8e1a-ac2e9e6da0ed.png)

I am attaching the two files I use as taring image and borehole information. 
The code looks like this

> TI1=npzread("flummy.npy")
TI1=TI1[:,:,4]
TI1= reshape(TI1,201,201,1)
geo=npzread("real_geo2.npy")
shape = HardData()
for i=1:size(geo,1)
    push!(shape, (geo[i,1]+1,geo[i,2]+1,1)=>geo[i,3])
end
reals= iqsim(TI1, 40, 40, 1, size(TI1)..., hard=shape, nreal=1)

[Data_for_Marios.zip](https://github.com/juliohm/ImageQuilting.jl/files/2306942/Data_for_Marios.zip)

**Comment by juliohm** [comment]
Hi @mariosgeo, thank you for reaching out.

I wouldn't recommend image quilting for dense hard data configurations. We investigated this issue in our [paper](https://www.researchgate.net/publication/317151543_Stochastic_Simulation_by_Image_Quilting_of_Process-based_Geological_Models?_sg=HlIUTVzG6iUMYJ-IbgfvO-zbrQ7caSmpLK3VCEj8mst6EWS9-p-bwSWHRdiTMuL77cj-2Upb0GHZ78uz_ga3-MLnT1S0a-DtSzbpp5K6.kplRcwPxlBGj44GiNJHPx2Hexnlp8q7nh9TP_YGtXryDK3XVJbaBgwO8pJqdavZeNu-VTqXTkotufSX1DQW9fw), which I am sharing here. It can work if you reduce the template size, but it becomes more computationally intensive. For dense hard data configurations, pixel-based algorithms like direct sampling are recommended. I didn't have the time to implement direct sampling yet, but meanwhile I think there is a Python implementation on the internet that one of my colleagues used.

If you are actually simulating a 3D domain or a very large 2D domain, then direct sampling and other existing pixel-based algorithms become too computationally intensive. I would try to reduce the template size and activate the GPU with image quilting to see if it helps: http://juliohm.github.io/ImageQuilting.jl/stable/gpu-support.html

Another parameter of image quilting that is set by default for the user, and that also impacts performance, is the overlap configuration. By default the overlaps are set to 1/6 of the template size, in your case ceil(1/6 * 40) --> 7. You may want to reduce this overlap region by decreasing the fraction further.

Please let me know if that clarifies the issue.

Best,

**Comment by mariosgeo** [comment]
Thanks for the reply and advice. 
I tried various  square template sizes (5,8,10,20,40,50, attached the one with template=10), with similar results.

![figure_1-2](https://user-images.githubusercontent.com/3422736/44446966-01248880-a5e7-11e8-96ee-de8bad469a43.png)

I tried also several overlap settings with the following loop (the title indicates the factor)


`for i=2:20
 reals= iqsim(TI1, 10, 10, 1, size(TI1)..., hard=shape,nreal=1,gpu=true,overlapx=1/i,overlapy=1/i,overlapz=1/i)

end`

![figure_1-3](https://user-images.githubusercontent.com/3422736/44448092-8b222080-a5ea-11e8-930a-96398827ce14.png)

Is there something more I can try?

**Comment by juliohm** [comment]
I am closing the issue. If you have questions again in the future, please ask in our gitter channel. The issue tracker on GitHub is mainly for bug reports and feature requests.

Thanks,

**Comment by mariosgeo** [comment]
Thanks for the help and reply
