### ISSUE TITLE
Tag a release that uses the new Images?

### ISSUE THREAD

**Issue by timholy** [juliohm/ImageQuilting.jl#5]
Hi @juliohm,

I had the impression you were using the new Images, but the released version of ImageQuilting apparently pins Images at its old version (https://github.com/JuliaImages/ImageFiltering.jl/issues/26#issuecomment-291000363). That means that anyone who installs ImageQuilting can't use the new version of Images. Apparently this is the last registered package that hasn't upgraded yet.

Can you release a new version that makes use of the new infrastructure?

**Comment by juliohm** [comment]
Hi Tim, I'll do it as soon as i get back to my computer.

**Comment by juliohm** [comment]
Hi @timholy, you mean the upper bound I put on Julia 0.6-? I don't specify the Images.jl version in the REQUIRE as you can see here:

https://github.com/juliohm/ImageQuilting.jl/blob/v0.4.3/REQUIRE

**Comment by timholy** [comment]
Yes, but @tkelman added one in METADATA (e.g., https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/ImageQuilting/versions/0.4.3/requires). Images 0.6 was tagged on Jan 30; your release of 0.4.3 came on Jan 29. In preparation for the breakages it would cause, we added the upper bounds because I think @tkelman determined that earlier releases were broken by the new Images, and we didn't want to break your package.

I just investigated myself, and I found that 0.4.3 *doesn't* work with Images 0.6 (and hence the upper bounds in METADATA are a good idea). However, the master branch of ImageQuilting *does* work with the new images. Hence, the best strategy is to make a new release of ImageQuilting and add a lower bound of 0.6 to Images (and no upper bound).

**Comment by tkelman** [comment]
The julia version upper bound is not really a good idea though and should probably be removed first. It would just mean on 0.6, the package (and Images etc) would get held back to the last version without an upper bound.

**Comment by juliohm** [comment]
Merged in METADATA, thank you.

**Comment by timholy** [comment]
Many thanks!
