### ISSUE TITLE
Visual regression tests failing on pkg.julialang.org

### ISSUE THREAD

**Issue by juliohm** [juliohm/ImageQuilting.jl#7]
Hi @tkelman, do you have a guess for what is causing this test failure on pkg.julialang.org?

http://pkg.julialang.org/logs/ImageQuilting_0.5.log

All visual tests pass locally on my laptop and on Travis CI:

https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/219012650

**Comment by tkelman** [comment]
Dunno. If you repeat the tests over and over again can you get a random failure? Seems intermittent, looking at the history from http://pkg.julialang.org/detail/ImageQuilting.html

**Comment by juliohm** [comment]
@tkelman I tried rebuilding multiple times, and everything is working on Travis CI. What is the difference between Travis CI and pkg.julialanguage.org builds?

**Comment by tkelman** [comment]
Everything. https://github.com/JuliaCI/PackageEvaluator.jl

**Comment by juliohm** [comment]
Thank you @tkelman , I am moving the issue to there.
