### ISSUE TITLE
GitHub page not displaying site

### ISSUE THREAD

**Issue by sbohora** [juliohm/ImageQuilting.jl#8]
@juliohm: I have a very similar structure of my Julia package as you do. I cannot have `gh-pages` to display my site. What is the easiest way to deploy Julia package in GitHub?
Thanks.

**Comment by juliohm** [comment]
Hi @sbohora, could you please share how you ended up finding ImageQuilting.jl?

I suggest you to take a look at the Documenter.jl package. As far as I remember, their documentation contains all the steps needed to setup GitHub and integrated documentation in Julia packages.

**Comment by sbohora** [comment]
I googled for similar issue which led to me to your repo. Thanks.
